[tools]
lefthook = "latest"
"npm:conventional-changelog-cli" = "latest"
"prettier" = "latest"

[tasks.changelog]
description = "通过 conventional-changelog-cli 生成变更日志"
run = [
  "conventional-changelog -i changelog.md -s -n conventional-changelog.config.json -k plugin.json -c plugin.json",
  "prettier -w changelog.md",
  "git add changelog.md"
]
